name: Deploy Frontend a EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      # NUEVO PASO: Obtener la contraseña desde GitHub en vez de EC2
      - name: Obtener Password ECR
        id: ecr-pwd
        run: echo "password=$(aws ecr get-login-password --region us-east-1)" >> $GITHUB_OUTPUT
        
      - name: Build y Push Frontend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: front-despacho
          IMAGE_TAG: latest
        run: |
          cd front_despacho
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
      - name: Despliegue en EC2 Frontend
        uses: appleboy/ssh-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_PASSWORD: ${{ steps.ecr-pwd.outputs.password }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ECR_REGISTRY, ECR_PASSWORD # Pasamos las variables al servidor
          script: |
            # Usamos la contraseña directamente sin necesidad de tener AWS CLI instalado
            echo $ECR_PASSWORD | sudo docker login --username AWS --password-stdin $ECR_REGISTRY
            sudo docker pull $ECR_REGISTRY/front-despacho:latest
            sudo docker stop front_web || true
            sudo docker rm front_web || true
            sudo docker run -d -p 80:80 --name front_web $ECR_REGISTRY/front-despacho:latest
